cleaned up robot-view and removed printf from video_listener

diff --git a/d_diff_drive_robot/robot-view b/d_diff_drive_robot/robot-view
--- a/d_diff_drive_robot/robot-view
+++ b/d_diff_drive_robot/robot-view
@@ -36,10 +36,14 @@ ln -s $ROBOT_PATH_MAIN ~/.gazebo/models/d_diff_drive_robot
 
 
 ROBOT_VIEW_VID_CHAN='robot-vid-chan'
+ROBOT_VIEW_CLIENT_FILE='robot-view-client.py'
 
+ROBOT_REMOTE_ADDRESS='0.0.0.0'
 
-HUBO_REMOTE_ADDRESS='0.0.0.0'
-
+FLAG_VIEW_CLIENT=1 #Default client
+FLAG_VIEW_SERVER=0
+FLAG_REMOTE=0
+FLAG_NOCONSOLE=0
 
 trim()
 {
@@ -83,7 +87,7 @@ RunViewClient()
    echo 'Starting hubo-view client process...'
 #   screen -S huboviewclient -d -m python $HUBO_VIEW_CLIENT_DIR
 #   python $HUBO_VIEW_CLIENT_DIR
-   python $HUBO_VIEW_DIR/$HUBO_VIEW_CLIENT_FILE
+   python $ROBOT_VIEW_DIR/$ROBOT_VIEW_CLIENT_FILE
 #   sleep 5
 #   if ! screen -list | grep -q "huboviewclient"; then
 #        echo 'hubo-view client started: FAIL'
@@ -94,18 +98,22 @@ RunViewClient()
 
 RunViewServer()
 {
+
+    gazebo model_diff_drive.world &
+    ./build/video_listener &
+
 #   cd /etc/hubo-ach
-   cd $HUBO_VIEW_DIR
-   echo 'Starting hubo-view server process...'
-   screen -S huboviewserver -d -m python $HUBO_VIEW_SERVER_FILE
+#   cd $HUBO_VIEW_DIR
+#   echo 'Starting hubo-view server process...'
+#   screen -S huboviewserver -d -m python $HUBO_VIEW_SERVER_FILE
 #   python $HUBO_VIEW_SERVER_DIR
 #   echo $HUBO_VIEW_SERVER_DIR
-   sleep 5
-   if ! screen -list | grep -q "huboviewserver"; then
-        echo 'hubo-view server started: FAIL'
-   else
-  	echo 'hubo-view server started: success'
-   fi
+#   sleep 5
+#   if ! screen -list | grep -q "huboviewserver"; then
+#        echo 'hubo-view server started: FAIL'
+#   else
+#  	echo 'hubo-view server started: success'
+#   fi
 }
 
 RunStatus()
@@ -147,23 +155,27 @@ KillAll()
         screen -S huboviewclient -p 0 -X quit
 	KillRemote
         sudo rm -r /dev/shm/achshm*
+        sudo kill -9 $(pidof video_listener)
+        sudo kill -9 $(pidof gzserver)
+        sudo kill -9 $(pidof gzclient)
+        sudo kill -9 $(pidof gazebo)
 }
 
 Install()
 {
 case "$1" in
         'install')
-                sudo mkdir $HUBO_DIR
-		sudo mkdir $HUBO_VIEW_DIR
-                sudo chmod -R 777 $HUBO_VIEW_DIR
-                cp $HUBO_VIEW_SERVER_FILE $HUBO_VIEW_DIR
-		cp $HUBO_VIEW_CLIENT_FILE $HUBO_VIEW_DIR
-                cp hubo-view $HUBO_VIEW_DIR
-                HUBO_VIEW_BIN="$HUBO_VIEW_DIR/hubo-view"
-                sudo ln -s $HUBO_VIEW_BIN /usr/bin/hubo-view
+                sudo mkdir $ROBOT_DIR
+		sudo mkdir $ROBOT_VIEW_DIR
+                sudo chmod -R 777 $ROBOT_VIEW_DIR
+                cp $ROBOT_VIEW_SERVER_FILE $ROBOT_VIEW_DIR
+		cp $ROBOT_VIEW_CLIENT_FILE $ROBOT_VIEW_DIR
+                cp hubo-view $ROBOT_VIEW_DIR
+                ROBOT_VIEW_BIN="$ROBOT_VIEW_DIR/hubo-view"
+                sudo ln -s $ROBOT_VIEW_BIN /usr/bin/hubo-view
 	;;
 	'remove')
-		sudo rm -R $HUBO_VIEW_DIR
+		sudo rm -R $ROBOT_VIEW_DIR
 		sudo rm /usr/bin/hubo-view
 	;;
         *)
@@ -196,9 +208,9 @@ ShowUsage()
 
 SetFlags()
 {
-HUBO_I=0
-HUBO_TEMP1="$@"
-HUBO_TEMP=($HUBO_TEMP1)
+ROBOT_I=0
+ROBOT_TEMP1="$@"
+ROBOT_TEMP=($ROBOT_TEMP1)
 for var in "$@"
 do
 #    echo "$var"
@@ -213,11 +225,11 @@ do
       ;;
       'remote' )
 	  FLAG_REMOTE=1
-          HUBO_REMOTE_ADDRESS=${HUBO_TEMP[$(($HUBO_I+1))]}
-	  echo "Remote address set: "$HUBO_REMOTE_ADDRESS
+          ROBOT_REMOTE_ADDRESS=${ROBOT_TEMP[$(($ROBOT_I+1))]}
+	  echo "Remote address set: "$ROBOT_REMOTE_ADDRESS
       ;;
     esac
-    HUBO_I=$(($HUBO_I+1))
+    ROBOT_I=$(($ROBOT_I+1))
 
 done
 }
@@ -240,7 +252,7 @@ case "$1" in
 	   if [[ $FLAG_REMOTE -eq 1 ]]
 	   then
 	       echo 'Starting remote connection'
-	       Remote $HUBO_REMOTE_ADDRESS
+	       Remote $ROBOT_REMOTE_ADDRESS
 	   fi
 	;;
 esac
